alias: Varmestyring 5
trigger:
  platform: state
  entity_id: 
    - sensor.temperature_5_xi
    - climate.danfoss_floorheater_target_5
action:
  service: climate.set_operation_mode
  data_template:
    entity_id: "climate.danfoss_floorheater_target_5"
    operation_mode: >-
      {% if (states('sensor.temperature_5_xi') | float) < (state_attr('climate.danfoss_floorheater_target_5','temperature') | float) %}
        Heat
      {% else %}
        Off
      {% endif %}