alias: Varmestyring 5
trigger:
  platform: numeric_state
  entity_id: 
    - sensor.temperatur_5_xi
    - climate.danfoss_floorheater_target_5.attributes.temperature
  action:
    service: climate.set_temperature
    data_template:
      entity_id: "climate.danfoss_floorheater_target_5"
      temperature: {{ states('sensor.temperatur_5_xi') }}
      operation_mode: > 
      {%if states('sensor.temperatur_5_xi') | float < states('climate.danfoss_floorheater_target_5.attributes.temperature') | float %}
      Heat
      {% else %}
      Off
      {%endif %}