alias: Varmestyring 5
trigger:
  platform: state
  entity_id: 
    - sensor.temperatur_5_xi
    - climate.danfoss_floorheater_target_5
action:
  service: climate.set_operation_mode
  data_template:
    entity_id: "climate.danfoss_floorheater_target_5"
    operation_mode: >
      {% if (states('sensor.temperatur_5_xi') | float) < (states('climate.danfoss_floorheater_target_5.attributes.temperature') | float) %}
        "Heat"
      {% else %}
        "Off"
      {% endif %}